### ISSUE TITLE
Please add a LICENSE to this project so others can contribute changes.

### ISSUE THREAD

**Issue by jaxzin** [ripclawffb/chocolatey-unreal-linux-toolchain#1]
As an employee of a corporation I can't contribute changes back to a project that has all rights reserved (the default position of source code if no license is present). We'd like to add support for v18.

**Comment by ripclawffb** [comment]
Added a license and updated unreal toolchain to v18. It's going through the package verification process now.

**Comment by jaxzin** [comment]
Thank you for the fast turnaround!
