### ISSUE TITLE
v20 is available and needs a package

### ISSUE THREAD

**Issue by jaxzin** [ripclawffb/chocolatey-unreal-linux-toolchain#2]
CDN location is https://cdn.unrealengine.com/CrossToolchain_Linux/v20_clang-13.0.1-centos7.exe

**Comment by ripclawffb** [comment]
Thank you for opening this issue. I have released a new version of the package. It is currently awaiting moderation.

https://community.chocolatey.org/packages/unreal-linux-toolchain/20.13.0.1
